# Form implementation generated from reading ui file 'HBPy_Session_Widgets.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MoleculeManager(object):
    def setupUi(self, MoleculeManager):
        MoleculeManager.setObjectName("MoleculeManager")
        MoleculeManager.resize(1125, 393)
        self.centralwidget = QtWidgets.QWidget(parent=MoleculeManager)
        self.centralwidget.setObjectName("centralwidget")
        self.WD_Btn_load_molecule = QtWidgets.QPushButton(parent=self.centralwidget)
        self.WD_Btn_load_molecule.setGeometry(QtCore.QRect(746, 10, 111, 25))
        self.WD_Btn_load_molecule.setObjectName("WD_Btn_load_molecule")
        self.WD_molecules_list = QtWidgets.QTableView(parent=self.centralwidget)
        self.WD_molecules_list.setGeometry(QtCore.QRect(6, 10, 711, 321))
        self.WD_molecules_list.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.AnyKeyPressed|QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked|QtWidgets.QAbstractItemView.EditTrigger.EditKeyPressed|QtWidgets.QAbstractItemView.EditTrigger.SelectedClicked)
        self.WD_molecules_list.setObjectName("WD_molecules_list")
        self.WD_Btn_alkyl_builder = QtWidgets.QPushButton(parent=self.centralwidget)
        self.WD_Btn_alkyl_builder.setGeometry(QtCore.QRect(747, 52, 112, 25))
        self.WD_Btn_alkyl_builder.setObjectName("WD_Btn_alkyl_builder")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(866, 60, 38, 17))
        self.label_2.setObjectName("label_2")
        self.WD_LE_smile = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.WD_LE_smile.setGeometry(QtCore.QRect(910, 52, 181, 25))
        self.WD_LE_smile.setObjectName("WD_LE_smile")
        MoleculeManager.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MoleculeManager)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1125, 22))
        self.menubar.setObjectName("menubar")
        MoleculeManager.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MoleculeManager)
        self.statusbar.setObjectName("statusbar")
        MoleculeManager.setStatusBar(self.statusbar)

        self.retranslateUi(MoleculeManager)
        QtCore.QMetaObject.connectSlotsByName(MoleculeManager)

    def retranslateUi(self, MoleculeManager):
        _translate = QtCore.QCoreApplication.translate
        MoleculeManager.setWindowTitle(_translate("MoleculeManager", "Molecule Manager"))
        self.WD_Btn_load_molecule.setText(_translate("MoleculeManager", "Load Molecule"))
        self.WD_Btn_alkyl_builder.setText(_translate("MoleculeManager", "Alkyl chain builder"))
        self.label_2.setText(_translate("MoleculeManager", "SMILE:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MoleculeManager = QtWidgets.QMainWindow()
    ui = Ui_MoleculeManager()
    ui.setupUi(MoleculeManager)
    MoleculeManager.show()
    sys.exit(app.exec())
