# Form implementation generated from reading ui file 'dvl.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MoleculeViewer(object):
    def setupUi(self, MoleculeViewer):
        MoleculeViewer.setObjectName("MoleculeViewer")
        MoleculeViewer.resize(896, 795)
        self.MoleculeDisplayArea = MoleculeGLWidget(parent=MoleculeViewer)
        self.MoleculeDisplayArea.setGeometry(QtCore.QRect(30, 20, 841, 641))
        self.MoleculeDisplayArea.setObjectName("MoleculeDisplayArea")
        self.WD_info = QtWidgets.QTextBrowser(parent=MoleculeViewer)
        self.WD_info.setGeometry(QtCore.QRect(30, 670, 841, 41))
        self.WD_info.setObjectName("WD_info")

        self.retranslateUi(MoleculeViewer)
        QtCore.QMetaObject.connectSlotsByName(MoleculeViewer)

    def retranslateUi(self, MoleculeViewer):
        _translate = QtCore.QCoreApplication.translate
        MoleculeViewer.setWindowTitle(_translate("MoleculeViewer", "Form"))
        self.WD_info.setHtml(_translate("MoleculeViewer", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Ctrl+left mouse button</span><span style=\" color:#e01b24;\"> to remove an atom                                 </span><span style=\" font-weight:600;\">Ctrl+right mouse button</span><span style=\" color:#e01b24;\"> to get atom info</span></p></body></html>"))
from HBPy.Molecule.MoleculeGLWidget.moleculeglwidget import MoleculeGLWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MoleculeViewer = QtWidgets.QWidget()
    ui = Ui_MoleculeViewer()
    ui.setupUi(MoleculeViewer)
    MoleculeViewer.show()
    sys.exit(app.exec())
